server:
  port: 80
spring:
  cloud:
    gateway:
      httpclient:
        host: proxy.iind.intel.com
        port: 911
      routes:
      - id: test_route
        uri: http://gaps.intel.com
        predicates:
        - Path=/test
        
