server:
  port: 8084

spring:
  cloud:
    config:
      server:
        native:
          search-locations: classpath:/shared
# git:
# uri: https://github.com/kbastani/spring-boot-microserviceconfig
  profiles:
    active: native      